
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuestionarioCOrg.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Departamento
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Departamento()
    {

        this.RespostaUsuario = new HashSet<RespostaUsuario>();

        this.Usuario = new HashSet<Usuario>();

    }


    public int dpt_id { get; set; }

    public string dpt_nome { get; set; }

    public System.DateTime dpt_dt_cadastro { get; set; }

    public bool dpt_ativo { get; set; }

    public int dpt_emp_id { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RespostaUsuario> RespostaUsuario { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Usuario> Usuario { get; set; }

    public virtual Empresa Empresa { get; set; }

}

}
