
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuestionarioCOrg.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class lead_empresa_lgpd
{

    public int id { get; set; }

    public string nome_completo { get; set; }

    public string email { get; set; }

    public string telefone { get; set; }

    public string nome_empresa { get; set; }

    public int qnt_colaborador { get; set; }

    public string cargo { get; set; }

    public string ramo { get; set; }

    public string dados_cliente { get; set; }

    public string compartilha_dados { get; set; }

    public string iniciou_adequacao { get; set; }

    public System.DateTime data_cadastro { get; set; }

    public string cidade { get; set; }

    public string estado { get; set; }

    public string formulario { get; set; }

    public string lead_hash { get; set; }

    public Nullable<int> etapa_chat { get; set; }

    public string lgpd_armazena_dados { get; set; }

    public string lgpd_situacao_ti { get; set; }

    public string lgpd_situacao_juridico { get; set; }

    public Nullable<int> lgpd_id_empresa { get; set; }

}

}
