
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuestionarioCOrg.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Pergunta
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Pergunta()
    {

        this.RespostaUsuario = new HashSet<RespostaUsuario>();

    }


    public int prg_id { get; set; }

    public Nullable<int> prg_numero { get; set; }

    public string prg_item { get; set; }

    public string prg_descricao { get; set; }

    public Nullable<int> prg_cls_id { get; set; }

    public int prg_qst_id { get; set; }

    public bool prg_ativo { get; set; }



    public virtual Classificacao Classificacao { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RespostaUsuario> RespostaUsuario { get; set; }

    public virtual Questionario Questionario { get; set; }

}

}
