

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuestionarioCOrg.DataAccess
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class QuestionarioOrgDBEntities : DbContext
{
    public QuestionarioOrgDBEntities()
        : base("name=QuestionarioOrgDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Classificacao> Classificacao { get; set; }

    public virtual DbSet<Departamento> Departamento { get; set; }

    public virtual DbSet<Media> Media { get; set; }

    public virtual DbSet<NivelAcesso> NivelAcesso { get; set; }

    public virtual DbSet<Resposta> Resposta { get; set; }

    public virtual DbSet<RespostaUsuario> RespostaUsuario { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    public virtual DbSet<Valor> Valor { get; set; }

    public virtual DbSet<Pergunta> Pergunta { get; set; }

    public virtual DbSet<Email> Email { get; set; }

    public virtual DbSet<EmailConfiguracao> EmailConfiguracao { get; set; }

    public virtual DbSet<EmpresaQuestionario> EmpresaQuestionario { get; set; }

    public virtual DbSet<Questionario> Questionario { get; set; }

    public virtual DbSet<Notificacoes> Notificacoes { get; set; }

    public virtual DbSet<Empresa> Empresa { get; set; }

    public virtual DbSet<lead_empresa_lgpd> lead_empresa_lgpd { get; set; }

}

}

