
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuestionarioCOrg.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Resposta
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Resposta()
    {

        this.RespostaUsuario = new HashSet<RespostaUsuario>();

        this.Valor = new HashSet<Valor>();

    }


    public int rsp_id { get; set; }

    public string rsp_valor { get; set; }

    public string rsp_descricao { get; set; }

    public int rsp_qst_id { get; set; }

    public bool rsp_ativo { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RespostaUsuario> RespostaUsuario { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Valor> Valor { get; set; }

    public virtual Questionario Questionario { get; set; }

}

}
