
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuestionarioCOrg.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Valor
{

    public int vlr_id { get; set; }

    public int vlr_rsp_id { get; set; }

    public string vlr_valor { get; set; }

    public System.DateTime vlr_dt_cadastro { get; set; }

    public bool vlr_ativo { get; set; }



    public virtual Resposta Resposta { get; set; }

}

}
