//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cel_20190520
    {
        public int id { get; set; }
        public string DDD { get; set; }
        public string Celular { get; set; }
        public string Segurado { get; set; }
        public string Sexo { get; set; }
        public string Nascimento { get; set; }
    }
}
