//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contato
    {
        public int cnt_id { get; set; }
        public string cnt_cpf { get; set; }
        public string cnt_par_id { get; set; }
        public string cnt_ddd { get; set; }
        public string cnt_fone { get; set; }
        public string cnt_celular { get; set; }
        public bool cnt_ativo { get; set; }
        public string cnt_ddd_celular { get; set; }
        public Nullable<int> cnt_seg_id { get; set; }
        public Nullable<int> cnt_dep_id { get; set; }
    
        public virtual Parentesco Parentesco { get; set; }
    }
}
