//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faturamento
    {
        public int fat_id { get; set; }
        public string fat_referencia { get; set; }
        public Nullable<decimal> fat_valor_faturamento { get; set; }
        public string fat_par_id { get; set; }
        public Nullable<short> fat_pla_tpp_id { get; set; }
        public Nullable<int> fat_quantidade { get; set; }
    
        public virtual Parentesco Parentesco { get; set; }
    }
}
