//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_LOCALIDADE
    {
        public LOG_LOCALIDADE()
        {
            this.LOG_BAIRRO = new HashSet<LOG_BAIRRO>();
            this.LOG_CPC = new HashSet<LOG_CPC>();
            this.LOG_FAIXA_LOCALIDADE = new HashSet<LOG_FAIXA_LOCALIDADE>();
            this.LOG_LOGRADOURO = new HashSet<LOG_LOGRADOURO>();
            this.LOG_UNID_OPER = new HashSet<LOG_UNID_OPER>();
            this.LOG_VAR_LOC = new HashSet<LOG_VAR_LOC>();
        }
    
        public int LOC_NU { get; set; }
        public string UFE_SG { get; set; }
        public string LOC_NO { get; set; }
        public string CEP { get; set; }
        public string LOC_IN_SIT { get; set; }
        public string LOC_IN_TIPO { get; set; }
        public Nullable<int> LOC_NU_SUB { get; set; }
        public string LOC_NO_ABREV { get; set; }
        public Nullable<int> MUN_NU { get; set; }
    
        public virtual ICollection<LOG_BAIRRO> LOG_BAIRRO { get; set; }
        public virtual ICollection<LOG_CPC> LOG_CPC { get; set; }
        public virtual ICollection<LOG_FAIXA_LOCALIDADE> LOG_FAIXA_LOCALIDADE { get; set; }
        public virtual ICollection<LOG_LOGRADOURO> LOG_LOGRADOURO { get; set; }
        public virtual ICollection<LOG_UNID_OPER> LOG_UNID_OPER { get; set; }
        public virtual ICollection<LOG_VAR_LOC> LOG_VAR_LOC { get; set; }
    }
}
