//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_FAIXA_UOP
    {
        public int UOP_NU { get; set; }
        public int FNC_INICIAL { get; set; }
        public int FNC_FINAL { get; set; }
    
        public virtual LOG_UNID_OPER LOG_UNID_OPER { get; set; }
    }
}
