//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NivelAcesso
    {
        public NivelAcesso()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int nvl_id { get; set; }
        public string nvl_descricao { get; set; }
        public System.DateTime nvl_dt_cadastro { get; set; }
        public bool nvl_bolAtivo { get; set; }
    
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
