//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parentesco
    {
        public Parentesco()
        {
            this.Contato = new HashSet<Contato>();
            this.Endereco = new HashSet<Endereco>();
            this.Faturamento = new HashSet<Faturamento>();
            this.Log = new HashSet<Log>();
            this.PlanoSegurado = new HashSet<PlanoSegurado>();
            this.ReajusteFaixaEtaria = new HashSet<ReajusteFaixaEtaria>();
            this.Segurado = new HashSet<Segurado>();
            this.Tipo_parentesco = new HashSet<Tipo_parentesco>();
        }
    
        public string par_id { get; set; }
        public string par_nome { get; set; }
        public bool par_ativo { get; set; }
    
        public virtual ICollection<Contato> Contato { get; set; }
        public virtual ICollection<Endereco> Endereco { get; set; }
        public virtual ICollection<Faturamento> Faturamento { get; set; }
        public virtual ICollection<Log> Log { get; set; }
        public virtual ICollection<PlanoSegurado> PlanoSegurado { get; set; }
        public virtual ICollection<ReajusteFaixaEtaria> ReajusteFaixaEtaria { get; set; }
        public virtual ICollection<Segurado> Segurado { get; set; }
        public virtual ICollection<Tipo_parentesco> Tipo_parentesco { get; set; }
    }
}
