//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanoSegurado
    {
        public int pls_id { get; set; }
        public int pls_seg_id { get; set; }
        public int pls_pla_id { get; set; }
        public bool pls_ativo { get; set; }
        public System.DateTime pls_timestamp { get; set; }
        public string pls_par_id { get; set; }
    
        public virtual Parentesco Parentesco { get; set; }
        public virtual Plano Plano { get; set; }
    }
}
