//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template
    {
        public Template()
        {
            this.HistoricoEvento = new HashSet<HistoricoEvento>();
            this.LayoutTemplate = new HashSet<LayoutTemplate>();
            this.RepositorioImportacao = new HashSet<RepositorioImportacao>();
        }
    
        public int tpl_id { get; set; }
        public string tpl_nome_template { get; set; }
        public string tpl_tipo_acao { get; set; }
        public string tpl_delimitador { get; set; }
        public string tpl_extensao { get; set; }
        public bool tpl_ativo { get; set; }
        public System.DateTime tpl_timestamp { get; set; }
        public Nullable<bool> tpl_padrao { get; set; }
    
        public virtual ICollection<HistoricoEvento> HistoricoEvento { get; set; }
        public virtual ICollection<LayoutTemplate> LayoutTemplate { get; set; }
        public virtual ICollection<RepositorioImportacao> RepositorioImportacao { get; set; }
    }
}
