//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionarioCOrg.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        public int mda_id { get; set; }
        public int mda_usu_id { get; set; }
        public string mda_item { get; set; }
        public Nullable<decimal> mda_valor_atual { get; set; }
        public Nullable<decimal> mda_valor_desejado { get; set; }
        public Nullable<System.DateTime> mda_dt_cadastro { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
