//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionarioCOrg.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classificacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Classificacao()
        {
            this.Pergunta = new HashSet<Pergunta>();
        }
    
        public int cls_id { get; set; }
        public string cls_nome { get; set; }
        public System.DateTime cls_dt_cadastro { get; set; }
        public bool cls_ativo { get; set; }
        public int cls_qst_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pergunta> Pergunta { get; set; }
        public virtual Questionario Questionario { get; set; }
    }
}
