//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionarioCOrg.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailConfiguracao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmailConfiguracao()
        {
            this.Email = new HashSet<Email>();
        }
    
        public int eml_id { get; set; }
        public string eml_smtp_cliente { get; set; }
        public int eml_smtp_cliente_porta { get; set; }
        public string eml_smtp_usuario { get; set; }
        public string eml_smtp_senha { get; set; }
        public System.DateTime eml_dt_cadastro { get; set; }
        public bool eml_ativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Email> Email { get; set; }
    }
}
