//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionarioCOrg.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaQuestionario
    {
        public int eqt_id { get; set; }
        public int eqt_emp_id { get; set; }
        public int eqt_qst_id { get; set; }
        public System.DateTime eqt_dt_cadastro { get; set; }
        public bool eqt_ativo { get; set; }
    
        public virtual Questionario Questionario { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
