//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionarioCOrg.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacoes
    {
        public int ntf_id { get; set; }
        public System.DateTime ntf_dt_visualizacao { get; set; }
        public int ntf_usu_id { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
