//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionarioCOrg.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Questionario()
        {
            this.Classificacao = new HashSet<Classificacao>();
            this.EmpresaQuestionario = new HashSet<EmpresaQuestionario>();
            this.Pergunta = new HashSet<Pergunta>();
            this.RespostaUsuario = new HashSet<RespostaUsuario>();
            this.Resposta = new HashSet<Resposta>();
        }
    
        public int qst_id { get; set; }
        public string qst_nome { get; set; }
        public System.DateTime qst_datacadastro { get; set; }
        public bool qst_ativo { get; set; }
        public bool qst_publicado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Classificacao> Classificacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpresaQuestionario> EmpresaQuestionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pergunta> Pergunta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RespostaUsuario> RespostaUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resposta> Resposta { get; set; }
    }
}
