//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionarioCOrg.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespostaUsuario
    {
        public int rpu_id { get; set; }
        public System.DateTime rpu_datacadastro { get; set; }
        public string rpu_valor_resposta { get; set; }
        public int rpu_usu_id { get; set; }
        public int rpu_rsp_id { get; set; }
        public int rpu_qst_id { get; set; }
        public int rpu_prg_id { get; set; }
        public int rpu_dpt_id { get; set; }
        public int rpu_emp_id { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Resposta Resposta { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Pergunta Pergunta { get; set; }
        public virtual Questionario Questionario { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
