//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acao
    {
        public Acao()
        {
            this.Log = new HashSet<Log>();
        }
    
        public int aco_id { get; set; }
        public string aco_nome { get; set; }
        public string aco_descricao { get; set; }
        public bool aco_ativo { get; set; }
    
        public virtual ICollection<Log> Log { get; set; }
    }
}
