//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banco
    {
        public Banco()
        {
            this.DadosCobranca = new HashSet<DadosCobranca>();
        }
    
        public string ban_id { get; set; }
        public string ban_descricao { get; set; }
        public bool ban_ativo { get; set; }
    
        public virtual ICollection<DadosCobranca> DadosCobranca { get; set; }
    }
}
