//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CEPEntities : DbContext
    {
        public CEPEntities()
            : base("name=CEPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ECT_PAIS> ECT_PAIS { get; set; }
        public DbSet<LOG_BAIRRO> LOG_BAIRRO { get; set; }
        public DbSet<LOG_CPC> LOG_CPC { get; set; }
        public DbSet<LOG_FAIXA_BAIRRO> LOG_FAIXA_BAIRRO { get; set; }
        public DbSet<LOG_FAIXA_CPC> LOG_FAIXA_CPC { get; set; }
        public DbSet<LOG_FAIXA_LOCALIDADE> LOG_FAIXA_LOCALIDADE { get; set; }
        public DbSet<LOG_FAIXA_UF> LOG_FAIXA_UF { get; set; }
        public DbSet<LOG_FAIXA_UOP> LOG_FAIXA_UOP { get; set; }
        public DbSet<LOG_GRANDE_USUARIO> LOG_GRANDE_USUARIO { get; set; }
        public DbSet<LOG_LOCALIDADE> LOG_LOCALIDADE { get; set; }
        public DbSet<LOG_LOGRADOURO> LOG_LOGRADOURO { get; set; }
        public DbSet<LOG_NUM_SEC> LOG_NUM_SEC { get; set; }
        public DbSet<LOG_TIPO_LOGRADOURO> LOG_TIPO_LOGRADOURO { get; set; }
        public DbSet<LOG_UNID_OPER> LOG_UNID_OPER { get; set; }
        public DbSet<LOG_VAR_BAI> LOG_VAR_BAI { get; set; }
        public DbSet<LOG_VAR_LOC> LOG_VAR_LOC { get; set; }
        public DbSet<LOG_VAR_LOG> LOG_VAR_LOG { get; set; }
    }
}
