//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECT_PAIS
    {
        public string PAI_SG { get; set; }
        public string PAI_SG_ALTERNATIVA { get; set; }
        public string PAI_NO_PORTUGUES { get; set; }
        public string PAI_NO_INGLES { get; set; }
        public string PAI_NO_FRANCES { get; set; }
        public string PAI_ABREVIATURA { get; set; }
    }
}
