//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_FAIXA_LOCALIDADE
    {
        public int LOC_NU { get; set; }
        public string LOC_CEP_INI { get; set; }
        public string LOC_CEP_FIM { get; set; }
    
        public virtual LOG_LOCALIDADE LOG_LOCALIDADE { get; set; }
    }
}
