//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_FAIXA_UF
    {
        public string UFE_SG { get; set; }
        public string UFE_CEP_INI { get; set; }
        public string UFE_CEP_FIM { get; set; }
    }
}
