//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_NUM_SEC
    {
        public int LOG_NU { get; set; }
        public string SEC_NU_INI { get; set; }
        public string SEC_NU_FIM { get; set; }
        public string SEC_IN_LADO { get; set; }
    
        public virtual LOG_LOGRADOURO LOG_LOGRADOURO { get; set; }
        public virtual LOG_LOGRADOURO LOG_LOGRADOURO1 { get; set; }
    }
}
