//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_UNID_OPER
    {
        public LOG_UNID_OPER()
        {
            this.LOG_FAIXA_UOP = new HashSet<LOG_FAIXA_UOP>();
        }
    
        public int UOP_NU { get; set; }
        public string UFE_SG { get; set; }
        public int LOC_NU { get; set; }
        public int BAI_NU { get; set; }
        public Nullable<int> LOG_NU { get; set; }
        public string UOP_NO { get; set; }
        public string UOP_ENDERECO { get; set; }
        public string CEP { get; set; }
        public string UOP_IN_CP { get; set; }
        public string UOP_NO_ABREV { get; set; }
    
        public virtual ICollection<LOG_FAIXA_UOP> LOG_FAIXA_UOP { get; set; }
        public virtual LOG_LOCALIDADE LOG_LOCALIDADE { get; set; }
    }
}
