//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_FAIXA_CPC
    {
        public int CPC_NU { get; set; }
        public string CPC_INICIAL { get; set; }
        public string CPC_FINAL { get; set; }
    
        public virtual LOG_CPC LOG_CPC { get; set; }
    }
}
