//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagamento
    {
        public int pag_id { get; set; }
        public int pag_seg_id { get; set; }
        public System.DateTime pag_data_vencimento { get; set; }
        public decimal pag_valor_vencimento { get; set; }
        public string pag_identificacao { get; set; }
        public Nullable<decimal> pag_valor_recebido { get; set; }
        public Nullable<decimal> pag_juros { get; set; }
        public string pag_tipo_baixa { get; set; }
        public int pag_spg_id { get; set; }
        public Nullable<System.DateTime> pag_data_baixa_pagamento { get; set; }
        public bool pag_ativo { get; set; }
        public System.DateTime pag_timestamp_baixa { get; set; }
        public int pag_pla_id { get; set; }
        public Nullable<System.DateTime> pag_data_pagamento { get; set; }
    
        public virtual Plano Plano { get; set; }
        public virtual Segurado Segurado { get; set; }
        public virtual StatusPagamento StatusPagamento { get; set; }
    }
}
