//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plano
    {
        public Plano()
        {
            this.Pagamento = new HashSet<Pagamento>();
            this.PlanoSegurado = new HashSet<PlanoSegurado>();
            this.PlanoFaixaEtaria = new HashSet<PlanoFaixaEtaria>();
            this.ReajusteFaixaEtaria = new HashSet<ReajusteFaixaEtaria>();
        }
    
        public int pla_id { get; set; }
        public string pla_nome { get; set; }
        public string pla_descricao { get; set; }
        public bool pla_ativo { get; set; }
        public int pla_tpp_id { get; set; }
    
        public virtual ICollection<Pagamento> Pagamento { get; set; }
        public virtual ICollection<PlanoSegurado> PlanoSegurado { get; set; }
        public virtual ICollection<PlanoFaixaEtaria> PlanoFaixaEtaria { get; set; }
        public virtual ICollection<ReajusteFaixaEtaria> ReajusteFaixaEtaria { get; set; }
        public virtual TipoPlano TipoPlano { get; set; }
    }
}
