//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profissao
    {
        public Profissao()
        {
            this.Dependente = new HashSet<Dependente>();
            this.Segurado = new HashSet<Segurado>();
        }
    
        public int prf_id { get; set; }
        public string prf_descricao { get; set; }
    
        public virtual ICollection<Dependente> Dependente { get; set; }
        public virtual ICollection<Segurado> Segurado { get; set; }
    }
}
