//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReajusteFaixaEtaria
    {
        public int rfe_id { get; set; }
        public int rfe_id_seg_dep { get; set; }
        public decimal rfe_valor_anterior { get; set; }
        public decimal rfe_valor_atualizado { get; set; }
        public int rfe_pla_id { get; set; }
        public string rfe_par_id { get; set; }
        public System.DateTime rfe_data_reajuste { get; set; }
        public bool rfe_ativo { get; set; }
    
        public virtual Parentesco Parentesco { get; set; }
        public virtual Plano Plano { get; set; }
    }
}
