//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segurado
    {
        public Segurado()
        {
            this.DadosCobranca = new HashSet<DadosCobranca>();
            this.Pagamento = new HashSet<Pagamento>();
        }
    
        public int seg_id { get; set; }
        public string seg_nome { get; set; }
        public string seg_cpf { get; set; }
        public string seg_par_id { get; set; }
        public int seg_tpa_id { get; set; }
        public System.DateTime seg_data_nascimento { get; set; }
        public decimal seg_valor_faixa { get; set; }
        public Nullable<System.DateTime> seg_dt_cadastro { get; set; }
        public Nullable<System.DateTime> seg_dt_atualiza_status { get; set; }
        public string seg_email { get; set; }
        public bool seg_ativo { get; set; }
        public Nullable<int> seg_prf_id { get; set; }
        public Nullable<System.DateTime> seg_dt_filiacao { get; set; }
        public string seg_sexo { get; set; }
        public string seg_nome_mae { get; set; }
        public string seg_nacionalidade { get; set; }
        public string seg_pispasep { get; set; }
        public string seg_dn { get; set; }
        public Nullable<int> seg_esp_id { get; set; }
        public string seg_cns { get; set; }
        public Nullable<int> seg_civ_id { get; set; }
        public Nullable<System.DateTime> seg_inicio_vigencia { get; set; }
        public Nullable<int> seg_for_id { get; set; }
        public Nullable<int> seg_cia_proposta { get; set; }
        public Nullable<int> seg_cia_id { get; set; }
        public Nullable<int> esp_id { get; set; }
        public Nullable<decimal> seg_num_filiacao { get; set; }
        public Nullable<decimal> seg_num_proposta { get; set; }
        public string seg_crm_estado { get; set; }
        public Nullable<int> seg_mdp_id { get; set; }
        public string seg_numero_carteira { get; set; }
        public Nullable<int> seg_crm { get; set; }
        public Nullable<decimal> seg_valor_odonto { get; set; }
    
        public virtual ICollection<DadosCobranca> DadosCobranca { get; set; }
        public virtual Especialidade Especialidade { get; set; }
        public virtual EstadoCivil EstadoCivil { get; set; }
        public virtual FormaPagamento FormaPagamento { get; set; }
        public virtual MelhorDiaPagamento MelhorDiaPagamento { get; set; }
        public virtual ICollection<Pagamento> Pagamento { get; set; }
        public virtual Parentesco Parentesco { get; set; }
        public virtual Profissao Profissao { get; set; }
        public virtual Seguradora Seguradora { get; set; }
        public virtual Tipo_parentesco Tipo_parentesco { get; set; }
    }
}
