//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SindicatoMedicoEntities : DbContext
    {
        public SindicatoMedicoEntities()
            : base("name=SindicatoMedicoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Acao> Acao { get; set; }
        public DbSet<Banco> Banco { get; set; }
        public DbSet<CicloFaturamento> CicloFaturamento { get; set; }
        public DbSet<Contato> Contato { get; set; }
        public DbSet<DadosCobranca> DadosCobranca { get; set; }
        public DbSet<Dependente> Dependente { get; set; }
        public DbSet<Endereco> Endereco { get; set; }
        public DbSet<Especialidade> Especialidade { get; set; }
        public DbSet<EstadoCivil> EstadoCivil { get; set; }
        public DbSet<Faturamento> Faturamento { get; set; }
        public DbSet<FormaPagamento> FormaPagamento { get; set; }
        public DbSet<HistoricoEvento> HistoricoEvento { get; set; }
        public DbSet<LayoutTemplate> LayoutTemplate { get; set; }
        public DbSet<Leads> Leads { get; set; }
        public DbSet<Log> Log { get; set; }
        public DbSet<MelhorDiaPagamento> MelhorDiaPagamento { get; set; }
        public DbSet<NivelAcesso> NivelAcesso { get; set; }
        public DbSet<Pagamento> Pagamento { get; set; }
        public DbSet<Parentesco> Parentesco { get; set; }
        public DbSet<Plano> Plano { get; set; }
        public DbSet<PlanoFaixaEtaria> PlanoFaixaEtaria { get; set; }
        public DbSet<PlanoSegurado> PlanoSegurado { get; set; }
        public DbSet<Profissao> Profissao { get; set; }
        public DbSet<ReajusteFaixaEtaria> ReajusteFaixaEtaria { get; set; }
        public DbSet<RepositorioImportacao> RepositorioImportacao { get; set; }
        public DbSet<Segurado> Segurado { get; set; }
        public DbSet<Seguradora> Seguradora { get; set; }
        public DbSet<StatusPagamento> StatusPagamento { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Template> Template { get; set; }
        public DbSet<Tipo_parentesco> Tipo_parentesco { get; set; }
        public DbSet<TipoPlano> TipoPlano { get; set; }
        public DbSet<tmpRepositorio> tmpRepositorio { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    
        [EdmFunction("SindicatoMedicoEntities", "fSplit")]
        public virtual IQueryable<fSplit_Result> fSplit(string @string, string separador)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("string", @string) :
                new ObjectParameter("string", typeof(string));
    
            var separadorParameter = separador != null ?
                new ObjectParameter("separador", separador) :
                new ObjectParameter("separador", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fSplit_Result>("[SindicatoMedicoEntities].[fSplit](@string, @separador)", stringParameter, separadorParameter);
        }
    
        public virtual ObjectResult<Prc_consolidado_faturamento_Result> Prc_consolidado_faturamento(Nullable<System.DateTime> dataIni, Nullable<System.DateTime> dataFim)
        {
            var dataIniParameter = dataIni.HasValue ?
                new ObjectParameter("DataIni", dataIni) :
                new ObjectParameter("DataIni", typeof(System.DateTime));
    
            var dataFimParameter = dataFim.HasValue ?
                new ObjectParameter("DataFim", dataFim) :
                new ObjectParameter("DataFim", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Prc_consolidado_faturamento_Result>("Prc_consolidado_faturamento", dataIniParameter, dataFimParameter);
        }
    
        public virtual ObjectResult<Prc_consolidado_pagamento_Result> Prc_consolidado_pagamento(Nullable<System.DateTime> dataIni, Nullable<System.DateTime> dataFim)
        {
            var dataIniParameter = dataIni.HasValue ?
                new ObjectParameter("DataIni", dataIni) :
                new ObjectParameter("DataIni", typeof(System.DateTime));
    
            var dataFimParameter = dataFim.HasValue ?
                new ObjectParameter("DataFim", dataFim) :
                new ObjectParameter("DataFim", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Prc_consolidado_pagamento_Result>("Prc_consolidado_pagamento", dataIniParameter, dataFimParameter);
        }
    
        public virtual ObjectResult<Prc_consolidado_segurado_Result> Prc_consolidado_segurado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Prc_consolidado_segurado_Result>("Prc_consolidado_segurado");
        }
    
        public virtual ObjectResult<Prc_detalhado_segurado_Result> Prc_detalhado_segurado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Prc_detalhado_segurado_Result>("Prc_detalhado_segurado");
        }
    
        public virtual int StpBaixaPagamentoAutomatico(Nullable<int> numTemplate, string anoMes)
        {
            var numTemplateParameter = numTemplate.HasValue ?
                new ObjectParameter("NumTemplate", numTemplate) :
                new ObjectParameter("NumTemplate", typeof(int));
    
            var anoMesParameter = anoMes != null ?
                new ObjectParameter("AnoMes", anoMes) :
                new ObjectParameter("AnoMes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StpBaixaPagamentoAutomatico", numTemplateParameter, anoMesParameter);
        }
    
        public virtual int StpGerarFaturamento()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StpGerarFaturamento");
        }
    
        public virtual int StpReajusteFaixaEtaria()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StpReajusteFaixaEtaria");
        }
    
        public virtual ObjectResult<Prc_Consolidado_Premio_Result> Prc_Consolidado_Premio()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Prc_Consolidado_Premio_Result>("Prc_Consolidado_Premio");
        }
    }
}
