//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_parentesco
    {
        public Tipo_parentesco()
        {
            this.Dependente = new HashSet<Dependente>();
            this.Segurado = new HashSet<Segurado>();
        }
    
        public int tpa_id { get; set; }
        public string tpa_par_id { get; set; }
        public string tpa_nome { get; set; }
        public bool tpa_ativo { get; set; }
    
        public virtual ICollection<Dependente> Dependente { get; set; }
        public virtual Parentesco Parentesco { get; set; }
        public virtual ICollection<Segurado> Segurado { get; set; }
    }
}
