//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Usuario
    {
        public Usuario()
        {
            this.HistoricoEvento = new HashSet<HistoricoEvento>();
            this.Log = new HashSet<Log>();
        }
    
        public int usr_id { get; set; }
        public string usr_nome { get; set; }
        public string usr_genero { get; set; }
        public string usr_cpf { get; set; }
        public System.DateTime usr_dt_cadastro { get; set; }
        public string usr_email { get; set; }
        public Nullable<System.DateTime> usr_dt_aprovado { get; set; }
        public string usr_aprovado { get; set; }
        public bool usr_deletado { get; set; }
        public string usr_senha { get; set; }
        public int usr_nvl_id { get; set; }
        public bool usr_atualiza_senha { get; set; }

        [NotMapped]
        public string MsgErro { get; set; }
        public string MsgErroSenha { get; set; }

        public virtual ICollection<HistoricoEvento> HistoricoEvento { get; set; }
        public virtual ICollection<Log> Log { get; set; }
        public virtual NivelAcesso NivelAcesso { get; set; }
    }
}
