//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_extracao_dados_gerenciais
    {
        public int vw_IdentificadorTitular { get; set; }
        public Nullable<int> vw_IdentificadorDependente { get; set; }
        public string vw_TipoPessoa { get; set; }
        public Nullable<int> vw_Produto { get; set; }
        public Nullable<int> vw_Plano { get; set; }
        public Nullable<bool> vw_StatusPlano { get; set; }
        public System.DateTime vw_DataCadastro { get; set; }
        public Nullable<bool> vw_Status { get; set; }
        public Nullable<System.DateTime> vw_DataAtualizaStatus { get; set; }
        public Nullable<decimal> vw_PremioSaude { get; set; }
        public decimal vw_PremioOdonto { get; set; }
        public string vw_DataVencimento { get; set; }
        public string vw_DataPagamento { get; set; }
        public decimal vw_ValorPago { get; set; }
        public decimal vw_ValorVencimento { get; set; }
        public int vw_StatusPagamento { get; set; }
    }
}
