//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Seguros.Proseg.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("API.Seguros.Proseg.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo {0} não informado..
        /// </summary>
        public static string ME001 {
            get {
                return ResourceManager.GetString("ME001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cálculo não retornado..
        /// </summary>
        public static string ME002 {
            get {
                return ResourceManager.GetString("ME002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato {0} inválido..
        /// </summary>
        public static string ME003 {
            get {
                return ResourceManager.GetString("ME003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veículo não retornado..
        /// </summary>
        public static string ME004 {
            get {
                return ResourceManager.GetString("ME004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desculpa, não conseguimos pesquisar a placa {0}. Por favor tente outra Placa..
        /// </summary>
        public static string ME005 {
            get {
                return ResourceManager.GetString("ME005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível Recalcular. Por favor, entre em contato com o Administrador...
        /// </summary>
        public static string ME006 {
            get {
                return ResourceManager.GetString("ME006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum registro encontrado..
        /// </summary>
        public static string ME007 {
            get {
                return ResourceManager.GetString("ME007", resourceCulture);
            }
        }
    }
}
