//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CicloFaturamento
    {
        public int cft_id { get; set; }
        public byte cft_dia_inicial { get; set; }
        public byte cft_dia_final { get; set; }
        public byte cft_dia_faturamento { get; set; }
        public byte cft_dia_reajuste { get; set; }
        public System.DateTime cft_timestamp { get; set; }
        public bool cft_ativo { get; set; }
    }
}
