//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DadosCobranca
    {
        public int dco_id { get; set; }
        public int dco_seg_id { get; set; }
        public string dco_agencia { get; set; }
        public string dco_conta { get; set; }
        public string dco_ban_id { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual Segurado Segurado { get; set; }
    }
}
