//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoEvento
    {
        public int hev_id { get; set; }
        public System.DateTime hev_DataEvento { get; set; }
        public string hev_NomeArquivo { get; set; }
        public int hev_tpl_id { get; set; }
        public short hev_StatusEvento { get; set; }
        public int hev_usr_id { get; set; }
        public string hev_MesReferencia { get; set; }
    
        public virtual Template Template { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
