//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leads
    {
        public int led_id { get; set; }
        public string led_nome { get; set; }
        public string led_crm { get; set; }
        public string led_telefone { get; set; }
        public string led_celular { get; set; }
        public string led_email { get; set; }
        public System.DateTime led_timestamp { get; set; }
        public bool led_ativo { get; set; }
    }
}
