//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_LOGRADOURO
    {
        public LOG_LOGRADOURO()
        {
            this.LOG_GRANDE_USUARIO = new HashSet<LOG_GRANDE_USUARIO>();
            this.LOG_VAR_LOG = new HashSet<LOG_VAR_LOG>();
        }
    
        public int LOG_NU { get; set; }
        public string UFE_SG { get; set; }
        public int LOC_NU { get; set; }
        public int BAI_NU_INI { get; set; }
        public Nullable<int> BAI_NU_FIM { get; set; }
        public string LOG_NO { get; set; }
        public string LOG_COMPLEMENTO { get; set; }
        public string CEP { get; set; }
        public string TLO_TX { get; set; }
        public string LOG_STA_TLO { get; set; }
        public string LOG_NO_ABREV { get; set; }
    
        public virtual ICollection<LOG_GRANDE_USUARIO> LOG_GRANDE_USUARIO { get; set; }
        public virtual LOG_LOCALIDADE LOG_LOCALIDADE { get; set; }
        public virtual LOG_NUM_SEC LOG_NUM_SEC { get; set; }
        public virtual LOG_NUM_SEC LOG_NUM_SEC1 { get; set; }
        public virtual ICollection<LOG_VAR_LOG> LOG_VAR_LOG { get; set; }
    }
}
