//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_VAR_LOG
    {
        public int LOG_NU { get; set; }
        public int VLO_NU { get; set; }
        public string TLO_TX { get; set; }
        public string VLO_TX { get; set; }
    
        public virtual LOG_LOGRADOURO LOG_LOGRADOURO { get; set; }
    }
}
