//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_GRANDE_USUARIO
    {
        public int GRU_NU { get; set; }
        public string UFE_SG { get; set; }
        public int LOC_NU { get; set; }
        public int BAI_NU { get; set; }
        public Nullable<int> LOG_NU { get; set; }
        public string GRU_NO { get; set; }
        public string GRU_ENDERECO { get; set; }
        public string CEP { get; set; }
        public string GRU_NO_ABREV { get; set; }
    
        public virtual LOG_LOGRADOURO LOG_LOGRADOURO { get; set; }
    }
}
