//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanoFaixaEtaria
    {
        public int pfe_id { get; set; }
        public int pla_id { get; set; }
        public int pfe_faixa_inicial { get; set; }
        public int pfe_faixa_final { get; set; }
        public decimal pfe_premio_total { get; set; }
        public System.DateTime pfe_data_alteracao { get; set; }
        public bool pfe_ativo { get; set; }
    
        public virtual Plano Plano { get; set; }
    }
}
