//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaAbsolutaWS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.absolutasolucoes.com.br/absoluta/", ConfigurationName="ConsultaAbsolutaWS.clsSicVinAgSoap")]
    public interface clsSicVinAgSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.absolutasolucoes.com.br/absoluta/InputSicVinAgRst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConsultaAbsolutaWS.struct_RespostaRst> InputSicVinAgRstAsync(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.absolutasolucoes.com.br/absoluta/InputSicVinAgDst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ConsultaAbsolutaWS.struct_RespostaDst> InputSicVinAgDstAsync(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.absolutasolucoes.com.br/absoluta/")]
    public partial class struct_RespostaRst
    {
        
        private struct_Identificacao identificacaoField;
        
        private struct_Controle controleField;
        
        private struct_RespostaFormatada respostaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public struct_Identificacao Identificacao
        {
            get
            {
                return this.identificacaoField;
            }
            set
            {
                this.identificacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public struct_Controle Controle
        {
            get
            {
                return this.controleField;
            }
            set
            {
                this.controleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public struct_RespostaFormatada Resposta
        {
            get
            {
                return this.respostaField;
            }
            set
            {
                this.respostaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.absolutasolucoes.com.br/absoluta/")]
    public partial class struct_Identificacao
    {
        
        private string nomeDaTransacaoField;
        
        private string descricaoDaTransacaoField;
        
        private string versaoDaTransacaoField;
        
        private System.DateTime dataDaPublicacaoField;
        
        private string autorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NomeDaTransacao
        {
            get
            {
                return this.nomeDaTransacaoField;
            }
            set
            {
                this.nomeDaTransacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DescricaoDaTransacao
        {
            get
            {
                return this.descricaoDaTransacaoField;
            }
            set
            {
                this.descricaoDaTransacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string VersaoDaTransacao
        {
            get
            {
                return this.versaoDaTransacaoField;
            }
            set
            {
                this.versaoDaTransacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime DataDaPublicacao
        {
            get
            {
                return this.dataDaPublicacaoField;
            }
            set
            {
                this.dataDaPublicacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Autor
        {
            get
            {
                return this.autorField;
            }
            set
            {
                this.autorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.absolutasolucoes.com.br/absoluta/")]
    public partial class struct_RespostaDst
    {
        
        private struct_Identificacao identificacaoField;
        
        private struct_Controle controleField;
        
        private ConsultaAbsolutaWS.ArrayOfXElement respostaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public struct_Identificacao Identificacao
        {
            get
            {
                return this.identificacaoField;
            }
            set
            {
                this.identificacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public struct_Controle Controle
        {
            get
            {
                return this.controleField;
            }
            set
            {
                this.controleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ConsultaAbsolutaWS.ArrayOfXElement Resposta
        {
            get
            {
                return this.respostaField;
            }
            set
            {
                this.respostaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.absolutasolucoes.com.br/absoluta/")]
    public partial class struct_Controle
    {
        
        private string clienteField;
        
        private string loginField;
        
        private string placaDeEntradaField;
        
        private string chassiDeEntradaField;
        
        private string iPdoComputadorConsumidorField;
        
        private string nomeDoComputadorProvedorField;
        
        private int codigoDeControleField;
        
        private e_Severidade severidadeField;
        
        private string descricaoField;
        
        private e_Acao acaoAdotadaField;
        
        private e_ResultadoDaPesquisa resultadoDaPesquisaField;
        
        private e_GravacaoDeLog gravacaoDoLogField;
        
        private System.DateTime dataExecucaoField;
        
        private long nrTransacaoField;
        
        private string observacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Cliente
        {
            get
            {
                return this.clienteField;
            }
            set
            {
                this.clienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Login
        {
            get
            {
                return this.loginField;
            }
            set
            {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PlacaDeEntrada
        {
            get
            {
                return this.placaDeEntradaField;
            }
            set
            {
                this.placaDeEntradaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ChassiDeEntrada
        {
            get
            {
                return this.chassiDeEntradaField;
            }
            set
            {
                this.chassiDeEntradaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string IPdoComputadorConsumidor
        {
            get
            {
                return this.iPdoComputadorConsumidorField;
            }
            set
            {
                this.iPdoComputadorConsumidorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NomeDoComputadorProvedor
        {
            get
            {
                return this.nomeDoComputadorProvedorField;
            }
            set
            {
                this.nomeDoComputadorProvedorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int CodigoDeControle
        {
            get
            {
                return this.codigoDeControleField;
            }
            set
            {
                this.codigoDeControleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public e_Severidade Severidade
        {
            get
            {
                return this.severidadeField;
            }
            set
            {
                this.severidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Descricao
        {
            get
            {
                return this.descricaoField;
            }
            set
            {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public e_Acao AcaoAdotada
        {
            get
            {
                return this.acaoAdotadaField;
            }
            set
            {
                this.acaoAdotadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public e_ResultadoDaPesquisa ResultadoDaPesquisa
        {
            get
            {
                return this.resultadoDaPesquisaField;
            }
            set
            {
                this.resultadoDaPesquisaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public e_GravacaoDeLog GravacaoDoLog
        {
            get
            {
                return this.gravacaoDoLogField;
            }
            set
            {
                this.gravacaoDoLogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime DataExecucao
        {
            get
            {
                return this.dataExecucaoField;
            }
            set
            {
                this.dataExecucaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public long NrTransacao
        {
            get
            {
                return this.nrTransacaoField;
            }
            set
            {
                this.nrTransacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Observacao
        {
            get
            {
                return this.observacaoField;
            }
            set
            {
                this.observacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.absolutasolucoes.com.br/absoluta/")]
    public enum e_Severidade
    {
        
        /// <remarks/>
        e0_NumeradorNaoInicializado,
        
        /// <remarks/>
        e1_MensagemDeInformacaoSimples,
        
        /// <remarks/>
        e2_MensagemDeAdvertencia,
        
        /// <remarks/>
        e3_MensagemDeErro,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.absolutasolucoes.com.br/absoluta/")]
    public enum e_Acao
    {
        
        /// <remarks/>
        e0_NumeradorNaoInicializado,
        
        /// <remarks/>
        e1_TrasacaoFoiExecutada,
        
        /// <remarks/>
        e2_TransacaoNaoFoiExecutada,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.absolutasolucoes.com.br/absoluta/")]
    public enum e_ResultadoDaPesquisa
    {
        
        /// <remarks/>
        e0_NumeradorNaoInicializado,
        
        /// <remarks/>
        e1_RegistrosForamLocalizados,
        
        /// <remarks/>
        e2_RegistrosNaoForamLocalizados,
        
        /// <remarks/>
        e3_RegistrosNemForamPesquisados,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.absolutasolucoes.com.br/absoluta/")]
    public enum e_GravacaoDeLog
    {
        
        /// <remarks/>
        e0_NumeradorNaoInicializado,
        
        /// <remarks/>
        e1_TransacaoFoiLogada,
        
        /// <remarks/>
        e2_TransacaoNaoFoiLogada,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.absolutasolucoes.com.br/absoluta/")]
    public partial class struct_RespostaFormatada
    {
        
        private string chassiField;
        
        private string fabricanteField;
        
        private string anoFabricacaoField;
        
        private string anoModeloField;
        
        private string combustivelField;
        
        private string quantidadeDeEixosField;
        
        private string tipoDaCarroceriaField;
        
        private string regiaoGeograficaField;
        
        private string paisField;
        
        private string localDaFabricaField;
        
        private string marcaField;
        
        private string modeloField;
        
        private string veiculoField;
        
        private string versaoField;
        
        private string motorField;
        
        private string tipoDoMotorField;
        
        private string tracaoField;
        
        private string transmissaoField;
        
        private string portasField;
        
        private string classificacaoField;
        
        private string comprimentoField;
        
        private string mesDeProducaoField;
        
        private string pesoBrutoField;
        
        private string tipoDeFreioField;
        
        private string digitoVerificadorField;
        
        private string verificacaoDoSerialField;
        
        private string distanciaEntreEixosField;
        
        private string codigoFipeField;
        
        private string conclusaoField;
        
        private string quantidadeIrregularidadesField;
        
        private string codigoIrregularidadeField;
        
        private string placaField;
        
        private string corField;
        
        private string advertenciaDenatranField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Chassi
        {
            get
            {
                return this.chassiField;
            }
            set
            {
                this.chassiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Fabricante
        {
            get
            {
                return this.fabricanteField;
            }
            set
            {
                this.fabricanteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AnoFabricacao
        {
            get
            {
                return this.anoFabricacaoField;
            }
            set
            {
                this.anoFabricacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AnoModelo
        {
            get
            {
                return this.anoModeloField;
            }
            set
            {
                this.anoModeloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Combustivel
        {
            get
            {
                return this.combustivelField;
            }
            set
            {
                this.combustivelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string QuantidadeDeEixos
        {
            get
            {
                return this.quantidadeDeEixosField;
            }
            set
            {
                this.quantidadeDeEixosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TipoDaCarroceria
        {
            get
            {
                return this.tipoDaCarroceriaField;
            }
            set
            {
                this.tipoDaCarroceriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string RegiaoGeografica
        {
            get
            {
                return this.regiaoGeograficaField;
            }
            set
            {
                this.regiaoGeograficaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Pais
        {
            get
            {
                return this.paisField;
            }
            set
            {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string LocalDaFabrica
        {
            get
            {
                return this.localDaFabricaField;
            }
            set
            {
                this.localDaFabricaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Marca
        {
            get
            {
                return this.marcaField;
            }
            set
            {
                this.marcaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Modelo
        {
            get
            {
                return this.modeloField;
            }
            set
            {
                this.modeloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Veiculo
        {
            get
            {
                return this.veiculoField;
            }
            set
            {
                this.veiculoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Versao
        {
            get
            {
                return this.versaoField;
            }
            set
            {
                this.versaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Motor
        {
            get
            {
                return this.motorField;
            }
            set
            {
                this.motorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string TipoDoMotor
        {
            get
            {
                return this.tipoDoMotorField;
            }
            set
            {
                this.tipoDoMotorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Tracao
        {
            get
            {
                return this.tracaoField;
            }
            set
            {
                this.tracaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Transmissao
        {
            get
            {
                return this.transmissaoField;
            }
            set
            {
                this.transmissaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Portas
        {
            get
            {
                return this.portasField;
            }
            set
            {
                this.portasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Classificacao
        {
            get
            {
                return this.classificacaoField;
            }
            set
            {
                this.classificacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Comprimento
        {
            get
            {
                return this.comprimentoField;
            }
            set
            {
                this.comprimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string MesDeProducao
        {
            get
            {
                return this.mesDeProducaoField;
            }
            set
            {
                this.mesDeProducaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string PesoBruto
        {
            get
            {
                return this.pesoBrutoField;
            }
            set
            {
                this.pesoBrutoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string TipoDeFreio
        {
            get
            {
                return this.tipoDeFreioField;
            }
            set
            {
                this.tipoDeFreioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string DigitoVerificador
        {
            get
            {
                return this.digitoVerificadorField;
            }
            set
            {
                this.digitoVerificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string VerificacaoDoSerial
        {
            get
            {
                return this.verificacaoDoSerialField;
            }
            set
            {
                this.verificacaoDoSerialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string DistanciaEntreEixos
        {
            get
            {
                return this.distanciaEntreEixosField;
            }
            set
            {
                this.distanciaEntreEixosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string CodigoFipe
        {
            get
            {
                return this.codigoFipeField;
            }
            set
            {
                this.codigoFipeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string Conclusao
        {
            get
            {
                return this.conclusaoField;
            }
            set
            {
                this.conclusaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string QuantidadeIrregularidades
        {
            get
            {
                return this.quantidadeIrregularidadesField;
            }
            set
            {
                this.quantidadeIrregularidadesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string CodigoIrregularidade
        {
            get
            {
                return this.codigoIrregularidadeField;
            }
            set
            {
                this.codigoIrregularidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string Placa
        {
            get
            {
                return this.placaField;
            }
            set
            {
                this.placaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string Cor
        {
            get
            {
                return this.corField;
            }
            set
            {
                this.corField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string AdvertenciaDenatran
        {
            get
            {
                return this.advertenciaDenatranField;
            }
            set
            {
                this.advertenciaDenatranField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface clsSicVinAgSoapChannel : ConsultaAbsolutaWS.clsSicVinAgSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class clsSicVinAgSoapClient : System.ServiceModel.ClientBase<ConsultaAbsolutaWS.clsSicVinAgSoap>, ConsultaAbsolutaWS.clsSicVinAgSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public clsSicVinAgSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(clsSicVinAgSoapClient.GetBindingForEndpoint(endpointConfiguration), clsSicVinAgSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public clsSicVinAgSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(clsSicVinAgSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public clsSicVinAgSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(clsSicVinAgSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public clsSicVinAgSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ConsultaAbsolutaWS.struct_RespostaRst> InputSicVinAgRstAsync(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi)
        {
            return base.Channel.InputSicVinAgRstAsync(pstrCliente, pstrLogin, pstrSenha, pstrPlaca, pstrChassi);
        }
        
        public System.Threading.Tasks.Task<ConsultaAbsolutaWS.struct_RespostaDst> InputSicVinAgDstAsync(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi)
        {
            return base.Channel.InputSicVinAgDstAsync(pstrCliente, pstrLogin, pstrSenha, pstrPlaca, pstrChassi);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.clsSicVinAgSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.clsSicVinAgSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.clsSicVinAgSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://webservices.absolutasolucoes.com.br/absoluta/clsSicVinAg.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.clsSicVinAgSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://webservices.absolutasolucoes.com.br/absoluta/clsSicVinAg.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            clsSicVinAgSoap,
            
            clsSicVinAgSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
